services:
  - type: web
    name: aina-api
    runtime: node
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_ISSUER
        value: aina-api
      - key: JWT_AUDIENCE
        value: aina-mobile
